name: emarket_user
description: A new Flutter restaurant application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

    cupertino_icons: ^1.0.0
    get_it: ^7.2.0
    provider: ^6.0.3
    shared_preferences: ^2.0.5
    dio: ^4.0.0-prev2
    image_picker: ^0.8.4+8
    pin_code_fields: ^7.0.0
    google_maps_flutter_web: ^0.4.0
    google_maps_flutter: ^2.0.3
    flutter_google_places: ^0.3.0
    geocoding: ^2.0.0
    geolocator: ^8.1.1
    shimmer_animation: ^2.0.0
    url_launcher: ^6.0.2
    webview_flutter: ^3.0.0
    firebase_core: ^1.7.0
    firebase_messaging: ^11.2.6
    flutter_local_notifications: ^9.3.2
    path_provider: ^2.0.1
    connectivity: ^3.0.3
    photo_view: ^0.14.0
    url_strategy: ^0.2.0
    carousel_slider: ^4.0.0
    fluro: ^2.0.3
    avatar_view: ^1.0.1
    universal_html: ^2.0.8
    universal_ui: ^0.0.8
    image: ^3.0.2
    flutter_widget_from_html_core: ^0.8.5+1
    phone_number: ^0.12.0+1
    country_code_picker: ^2.0.2
    flutter_typeahead: ^4.0.0
    fwfh_selectable_text: ^0.8.3+1
    intl_phone_field: ^3.1.0
    font_awesome_flutter: ^10.3.0
    flutter_svg: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700